### ISSUE TITLE
1.12.2: About mob spawns, region teleports and reinforcements

### ISSUE THREAD

**Issue by TeQTabanca** [kangarko/Boss#1106]
### 1- After adding any mob to the reinforcement section, after killing the mob I set, the mob in the reinforcement will spawn next to the dead mob, but I want it to spawn where it died.

https://user-images.githubusercontent.com/89253304/191807420-9edb7803-9911-480a-917e-7097b60c5680.mp4

### 2- When I try to teleport to the zone, I teleport to the lower part of the zone.

https://user-images.githubusercontent.com/89253304/191807455-31d642b3-131a-4770-99ca-e8b237117030.mp4

### 3- i'm setting the mob instead of spawn, but the mob looks in different places when it's in the AI feature.

![boss mob spawn](https://user-images.githubusercontent.com/89253304/191806491-8256fc65-67a8-4e12-aed6-9ab1f695d0df.png)

### 4- [BUG] When I add the spawn type to the spawning section and close the menu and come back to the spawning section, the spawn type I added does not appear.

https://user-images.githubusercontent.com/89253304/191809012-ae741681-bfe8-4203-be32-d8fcc748b756.mp4

**Comment by kangarko** [comment]
1 - I will make the random offset 10X smaller, thanks.

2 - Should be fixed 

3 - When citizens is enabled we copy where you are looking, simply look where you want mob to look

4 - Thanks I will fix that

**Comment by TeQTabanca** [comment]
### I tested the new version but

### 1- Reinforcements problem still persists. ([Video](https://www.dropbox.com/s/u6oq00md3f9oz3a/boss%20reinforcements.mp4?dl=0))

### 2- Teleport problem solved.

### 3- I no longer use the Citizens plugin. Can you get the mobs to look straight and stand right in the middle of the block?

![image](https://user-images.githubusercontent.com/89253304/192534328-1a6de68a-8e67-44f9-852a-80b83c85f011.png)


### 4- After adding the spawn type, it still shows up in the Spawning section when I try to delete it, and if I try to delete it one more time, it gives an error in the console.

### Note: I retested it to explain with video but it seems to be working fine now but I'll still send you the errors.

### Console:
```
[14:37:23 ERROR]: Boss 4.5.3 encountered a FoException! Please check your error.log and report this issue with the information in that file. Running CraftBukkit 1.12.2-R0.1-SNAPSHOT and Java 11.0.13
[14:37:23 INFO]: org.mineacademy.boss.lib.exception.FoException: Report: Spawnrul test not loaded. Available: []
[14:37:23 INFO]:        at org.mineacademy.boss.lib.Valid.checkNotNull(Valid.java:61)
[14:37:23 INFO]:        at org.mineacademy.boss.lib.settings.ConfigItems.removeItemByName(ConfigItems.java:269)
[14:37:23 INFO]:        at org.mineacademy.boss.lib.settings.ConfigItems.removeItem(ConfigItems.java:259)
[14:37:23 INFO]:        at org.mineacademy.boss.spawn.SpawnRule.removeRule(SpawnRule.java:885)
[14:37:23 INFO]:        at org.mineacademy.boss.menu.SelectSpawnRuleMenu$IndividualSpawningMenu.lambda$new$0(SelectSpawnRuleMenu.java:212)
[14:37:23 INFO]:        at org.mineacademy.boss.lib.menu.button.ButtonRemove$RemoveConfirmButton.onClickedInMenu(ButtonRemove.java:136)
[14:37:23 INFO]:        at org.mineacademy.boss.lib.menu.Menu.onButtonClick(Menu.java:1076)
[14:37:23 INFO]:        at org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:96)
[14:37:23 INFO]:        at jdk.internal.reflect.GeneratedMethodAccessor558.invoke(Unknown Source)
[14:37:23 INFO]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:37:23 INFO]:        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[14:37:23 INFO]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[14:37:23 INFO]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[14:37:23 INFO]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[14:37:23 INFO]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[14:37:23 INFO]:        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[14:37:23 INFO]:        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[14:37:23 INFO]: [Boss] !-----------------------------------------------------!
[14:37:23 INFO]: [Boss]  Error clicking in menu MenuDialogRemove{}
[14:37:23 INFO]: [Boss] !-----------------------------------------------------!
```

### .Log File:
```
More Information: 
Spawnrul test not loaded. Available: []
FoException Report: Spawnrul test not loaded. Available: []
	 at org.mineacademy.boss.lib.Valid.checkNotNull(Valid.java:61)
	 at org.mineacademy.boss.lib.settings.ConfigItems.removeItemByName(ConfigItems.java:269)
	 at org.mineacademy.boss.lib.settings.ConfigItems.removeItem(ConfigItems.java:259)
	 at org.mineacademy.boss.spawn.SpawnRule.removeRule(SpawnRule.java:885)
	 at org.mineacademy.boss.menu.SelectSpawnRuleMenu$IndividualSpawningMenu.lambda$new$0(SelectSpawnRuleMenu.java:212)
	 at org.mineacademy.boss.lib.menu.button.ButtonRemove$RemoveConfirmButton.onClickedInMenu(ButtonRemove.java:136)
	 at org.mineacademy.boss.lib.menu.Menu.onButtonClick(Menu.java:1076)
	 at org.mineacademy.boss.lib.menu.MenuListener.onMenuClick(MenuListener.java:96)
	 at jdk.internal.reflect.GeneratedMethodAccessor558.invoke(Unknown Source)
	 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
	 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
	 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
	 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
----------------------------------------------------------------------------------------------
```

**Comment by kangarko** [comment]
1 - Yes as explained this will happen naturally, we cannot collide the entities otherwise bugs would occur.

3 - I will make the mobs look in the four world directions in the next update but keep in mind if you don't  disable their AI, they will rotate however they want and it may not work on 1.12.

4 - I cant reproduce, can you send a video?

**Comment by TeQTabanca** [comment]
### 1- The reinforcements feature was working fine in Boss-3.10.4 version. Finally, if I add the monster egg to the reinforcements section and return, the monster egg I set will disappear.

https://user-images.githubusercontent.com/89253304/193135891-6f0c69ce-cf1d-4cc6-b75c-4a2f0e48a47c.mp4

### 3- No hassle. At least we'll have tried.

### 4- It seems to work just fine when I try it now. Finally, sometimes when adding spawn rule, it doesn't automatically select the mob I set.

https://user-images.githubusercontent.com/89253304/193137462-631627e5-b917-4ae5-9617-69760051895f.mp4

**Comment by kangarko** [comment]
1 and 4 - Should be fixed in the next version, I found the problem!

**Comment by TeQTabanca** [comment]
### I tested the new version but

### 1- Reinforcements now saves the mob egg, but when the monster spawns after death, the movement problem still persists and after a while, if there are blocks in the direction it is going, it can spawn in it.

https://user-images.githubusercontent.com/89253304/193321760-97a78621-0f0d-4e7a-8ec8-a3b34f5cf967.mp4

### 4- The problem still continues. I think I found the problem. You will understand better in the video.

https://user-images.githubusercontent.com/89253304/193327625-171de3d2-0e61-484b-b023-fb684b32f661.mp4

### 5- Spawning section "All mob rules" Any chance of adding a section called? Because after adding a mob rule, I can only see all the mob rules when I click on the Return option.

**Comment by TeQTabanca** [comment]
### 6- By the way, I set the dragon's exp to 0, but the exp continues to decrease.


https://user-images.githubusercontent.com/89253304/194055695-f556763f-6631-4326-a0ff-7b9f78b410b9.mp4

**Comment by kangarko** [comment]
Hey and sorry for the delay, I will investigate in 24h!

**Comment by kangarko** [comment]
1 - Thanks, this should be completely fixed in the next update, sorry that it took this long.
4 - I should fix it now :) If not then it is not a priority since it is a minor issue and taking too much of my time
5 - I the main menu /boss menu > Spawning you should see all spawning rules for all mobs
6 - Unfortunately this seems to be controlled by some other game mechanics for which we have no access for ?

**Comment by TeQTabanca** [comment]
### 5- I never noticed. Sorry. It might be better if you add it to the spawning section.
### 6- I tried it on the test server and got the same result. There was only ItemEdit and your plugin.Have you tested it on the 1.12.2-Spigot server?

**Comment by TeQTabanca** [comment]
### 7- [Suggestion] It would be nice if you register these placeholders in the PlaceholderAPI plugin, because these placeholders will be useful for use in plugins that support PlaceholderAPI.This is a necessary suggestion.
- A placeholder that tells you how many entities you've killed.
Example: 
**%boss_player_<entity_types>(CREEPER)_kills%**, 
**%boss_player_<created_entities>(Names of .yml files in Bosses section in Boss file)_kills%**,
**%boss_player_all_animals_kills%**(Placeholder for all animals you kill)
**%boss_player_all_mobs_kills%**(Placeholder for all mobs you kill)
**%boss_player_all_entities_kills%**(Placeholder for all entities you kill)
- It would also be nice to have a placeholder to see how many entities there are all over the world.
Example:
**%boss_spawn_<entity_types>(CREEPER)_in_<world_names>(WORLD-1),<world_names>(WORLD-2)...%**,
**%boss_spawn_<created_entities>(Names of .yml files in Bosses section in Boss file)_in_<world_names>(WORLD-1),<world_names>(WORLD-2)...%**,
**%boss_spawn_all_entities_in_<world_names>(WORLD-1),<world_names>(WORLD-2)...%**
**%boss_spawn_all_animals_in_all_worlds%**
**%boss_spawn_all_mobs_in_all_worlds%**
**%boss_spawn_all_entities_in_all_worlds%**
- For players with the most kills
Example:
**%boss_top:<1-10>_<entity_types>_kills_amount%**,
**%boss_top:<1-10>_<created_entities>_kills_amount%**,
**%boss_top:<1-10>_all_animals_kills_amount%**,
**%boss_top:<1-10>_all_mobs_kills_amount%**,
**%boss_top:<1-10>_all_entities_kills_amount%**,
**%boss_top:<1-10>_<entity_types>_kills_player_name%**,
**%boss_top:<1-10>_<created_entities>_kills_player_name%**,
**%boss_top:<1-10>_all_animals_kills_player_name%**,
**%boss_top:<1-10>_all_mobs_kills_player_name%** and
**%boss_top:<1-10>_all_entities_kills_player_name%**

**Comment by TeQTabanca** [comment]
### 8- [Question]-[Suggestion] When I spawn the mob named Wither, the bossbar appears directly, but when I spawn the ender dragon, the bossbar does not appear directly, it appears when I restart the server. Do these mobs have a feature to disable their bossbar? If yes, any chance to add?

**Comment by kangarko** [comment]
Sorry for the delay!

5 Thanks for your suggestion
6 I did not, we only test on 1.8.8 and 1.19, I dont have the time/capacity to test on dozens of versions, sorry. That server version appears to have that issue.
7 and 8, Thanks for your suggestion, going to put it down to roadmap but at present we have no ETA :(

**Comment by TeQTabanca** [comment]
### 6- I found a solution but it runs the command after it dies because the dragon has a dying animation. Any chance of adding the ability to use the command after a few seconds as a solution? Namely the "Command Delay" feature.

### 9- [BUG] When I click Return after setting the exp of the entity, it doesn't save the exp I set and it becomes the old exp. If I press the ESC key after setting the solution exp, the exp will be saved.

https://user-images.githubusercontent.com/89253304/196723994-4b0b6f4f-0d84-44a8-9b5e-0809552a7aa5.mp4

**Comment by TeQTabanca** [comment]
10- I turn on the Random Equipment feature but nothing happens. If I manually give equipment, open Random Equipment feature and save, remove and save manually adjusted equipment, the equipment I manually adjusted will remain on the asset. (You will understand better in the video.)


https://user-images.githubusercontent.com/89253304/196875166-9b28f16b-7424-4063-b951-3573950a4266.mp4

**Comment by kangarko** [comment]
6 - Thanks, I will note this as suggestion.

9 - Thank you I have fixed this!

10 - Yes, sadly we have to NOT remove our equipment because it would also remove Minecraft's random equipment. Just disable that option to reset the mob's equipment.

11 - I apology, this might be related to 1.12 limitation, I need to investigate further when I have more time.

**Comment by TeQTabanca** [comment]
### 10- Even if I add Equipment, it doesn't give the asset randomly every time it spawns.

https://user-images.githubusercontent.com/89253304/197290381-b33712b0-1f19-43f4-8995-e0b0ad9b6df2.mp4


### 11- I tried it on the test server, it works, but when the entity rides the zombie horse and skeleton horse, it walks and then disappears. (Even when No AI is on) 
### -- If I add too many assets, it will overlap. ([Video](https://www.dropbox.com/s/joxz65xybapshr7/boss%20riding%20feature%20issue%201.mp4?dl=0))
### -- Finally it is controlled by the entity it is riding. ([Video](https://www.dropbox.com/s/3bb21b1lomn4ehh/boss%20riding%20feature%20issue%202.mp4?dl=0))

### 12-It would be nice if we could set what color the entities have when turning on the glow feature.

**Comment by kangarko** [comment]
10 - This is intended, you need to disable Random Equipment if you want bosses to have your own custom one.

11 - What MC version did you test on? I believe 1.12 can only ride one mob maximum. There are some limitations and AI bugs related to riding multiple monsters tho.

12 - Thanks for your suggestion! This is done with the scoreboard and we found out it was quite difficult to do without conflicts with other plugins so right now we do not plan on adding it.

**Comment by TeQTabanca** [comment]
### 10- I mean, I want mob to have random armor sets every time he spawns, but every time he spawns he gets the same armor set. What is the problem caused by?

### 11- I'm using the "1.12.2-Spigot" version, but I also tried the "1.12.2 Paper-Spigot" version and the result did not change.

**Comment by kangarko** [comment]
10 - Hmm that feature we don't have in Boss, you can resort to using Natural Equipment, but then you need to remove all of our custom equipment from the menu.

11 - Yes the entire 1.12 does not support riding multiple entities.
