### ISSUE TITLE
Boss region not spawning

### ISSUE THREAD

**Issue by stefann231** [kangarko/Boss#390]
I made a boss region and a world guard region in one chunk, set the conditions and which boss should spawn but it's still not spawning, maybe i set the conditions wrong? I tried doing exact Light Level and exact Height (Y) and exact time but it's still not working

**Comment by kangarko** [comment]
Please see https://github.com/kangarko/Boss/wiki/Common-Issues#bosses-are-not-spawning-naturally as well as the question below and complete all steps.

**Comment by kangarko** [comment]
Closing in good faith this has been resolved, comment below if otherwise

**Comment by stefann231** [comment]
Still not working but alright

mie., 31 iul. 2019, 16:51 Matej <notifications@github.com> a scris:

**Comment by kangarko** [comment]
Please post me your Boss/ folder as a ZIP.

**Comment by stefann231** [comment]
It's actually the default folder,

mie., 31 iul. 2019, 17:16 Matej <notifications@github.com> a scris:

**Comment by kangarko** [comment]
You said you changed the conditions and set up a region. Any change in the plugin will alter your settings and / or data.db. If you want this solved, post me your folder please.

**Comment by stefann231** [comment]
Sure i'll post it when i get home

joi, 1 aug. 2019, 16:32 Matej <notifications@github.com> a scris:

**Comment by stefann231** [comment]
Sorry for the late reply, here's the boss zip

În joi, 1 aug. 2019 la 16:33, Stefan Beleaua <stefanromeo85@gmail.com> a
scris:

**Comment by kangarko** [comment]
Sorry the email attachment got lost, please use uploadfiles.io to upload your folder.

**Comment by stefann231** [comment]
https://ufile.io/3bc00omk here's the file

În sâm., 3 aug. 2019 la 17:18, Matej <notifications@github.com> a scris:

**Comment by kangarko** [comment]
The 're' boss has ROOFED_FOREST biome selected - he will only spawn in that one biome and nowhere else.

The other 'ta' Boss should spawn in the Boss 'nou' region as well as the 'test' WorldGuard region

Finally, you have Timed_Spawning.Delay to 90 seconds - you can try setting it to 5 seconds to see more Bosses if they spawn.

You can also set Debug to [spawning] in settings.yml and check why your bosses are/are not spawning in the console.

**Comment by stefann231** [comment]
Yeah the current biome that i am trying to spawn in is roofed forest, when
i get home i will try and do the debug

mar., 6 aug. 2019, 17:17 Matej <notifications@github.com> a scris:

**Comment by kangarko** [comment]
Closing due to inactivity, comment below if you get the debugs
