### ISSUE TITLE
1.17.1 Citizen pathfinder and AI

### ISSUE THREAD

**Issue by morphin06** [kangarko/Boss#936]
I create a boss pigs that attack player. for AI
But pig he just keep following the player and didn't  and received a warn in my console.
i also tried chicken. but it is they same error.
https://pastebin.com/Jxz8PiKN

**Comment by dinobossytnew** [comment]
BOSS has its own log, would you like to pass it on?

**Comment by morphin06** [comment]
https://pastebin.com/iwEFvAzb

**Comment by ElBananaa** [comment]
Hey!
It looks like you're using a spigot/paper alternative named light, which may be the cause of your issue.
Please try with an official Paper version to see if your issue still happens.

Please note that due to the high amount of forks/alternatives to spigot/paper, we most likely won't add support for any of these alternatives unless it's a highly requested thing.
In the meantime, please refer to our wiki page to get an exact list of available and working alternatives: https://github.com/kangarko/Boss/wiki/Compatibility#variants-of-bukkit

**Comment by kangarko** [comment]
Use the next version. We also fixed the "Menu title cannot be longer than" error.

**Comment by kangarko** [comment]
If still getting errors, use Paper.

**Comment by morphin06** [comment]
> If still getting errors, use Paper.

I still have the error even i used Paper 1.17.1
and have this Spam console error until the server crashed https://pastebin.com/1BJns8qy

Server version 

[00:15:33] [Server thread/INFO]: This server is running Paper version git-Paper-353 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: f2cb9cb)

**Comment by morphin06** [comment]
I don't know why they closed this ticket even it isn't fix
